config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  resources :u, only: %i[show edit update] do
    member do
      get :following
      get :followers
    end
  end
  resources :following, only: %i[destroy] do
    member do
      get :add # Use get instead of create so it can store redirect
      post :approve
      post :unapprove
    end
  end

  resources :quizzes, only: %i[index show update]

  root "landing#index"

  get "/about", to: "landing#about"
  get "/privacy", to: "landing#privacy"
  get "/support", to: "landing#support"
  get "/browser_extensions", to: "landing#browser_extensions"
  get "/browser_extension", to: redirect("browser_extensions")
  get "/browser_extension_auth", to: "landing#browser_extension_auth"

  resources :ratings, except: [:show] do
    collection { post :add_topic }
  end

  resources :reviews, only: %i[index show update]

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resource :auth, only: [:create] do
        collection { get :status }
      end
      resources :reviews, only: [:create]
      resources :ratings, only: [:create, :show]
      resources :citations, only: %i[index show] do
        collection { post :filepath }
      end

      match "*a", via: [:get, :post, :put, :patch, :delete], to: "api_v1#not_found"
    end
  end

  namespace :admin do
    root to: "ratings#index"
    resources :users, only: %i[index edit update destroy]
    resources :topics
    resources :topic_reviews, except: [:show]
    resources :topic_review_citations, only: %i[edit update]
    resources :citations, only: %i[index edit update show]
    resources :ratings, only: %i[index show update destroy]
    resources :publishers, only: %i[index edit update show]
    resources :quizzes, except: [:destroy]
    resources :quiz_responses, only: [:index]
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/controllers/admin/topic_reviews_controller.rb
class Admin::TopicReviewsController < Admin::BaseController
  include TranzitoUtils::SortableTable

  before_action :set_period, only: [:index]
  before_action :find_topic_review, only: %i[edit update destroy]

  def index
    page = params[:page] || 1
    @per_page = params[:per_page] || 25
    @topic_reviews = searched_topic_reviews.reorder(order_scope_query)
      .includes(:topic, :topic_review_votes).page(page).per(@per_page)
  end

  def new
    @topic_review = TopicReview.new
  end

  def create
    @topic_review = TopicReview.new(permitted_params)
    if @topic_review.save
      flash[:success] = "Review created"
      redirect_to admin_topic_reviews_path, status: :see_other
    else
      render :new, status: :see_other
    end
  end

  def edit
    page = params[:page] || 1
    @per_page = params[:per_page] || 50
    @topic_review_citations = @topic_review.topic_review_citations.vote_ordered
      .includes(:topic_review_votes, :citation)
      .page(page).per(@per_page)
    @topic_review_votes = searched_topic_review_votes
      .includes(:rating, :user)
      .page(page).per(@per_page)
  end

  def update
    if @topic_review.update(permitted_params)
      flash[:success] = "Review updated"
      redirect_to admin_topic_reviews_path, status: :see_other
    else
      render :edit, status: :see_other
    end
  end

  def destroy
    if @topic_review.destroy
      flash[:success] = "Topic review deleted"
    else
      flash[:error] = "Unable to delete Topic review!"
    end
    redirect_back(fallback_location: admin_topic_reviews_path, status: :see_other)
  end

  private

  def sortable_columns
    %w[created_at updated_at topic_name start_at end_at]
  end

  def order_scope_query
    if sort_column == "name"
      # IDK, send is scary, add protection
      raise "Invalid sort_direction" unless %w[asc desc].include?(sort_direction)
      TopicReview.arel_table["topic_name"].lower.send(sort_direction)
    else
      "topic_reviews.#{sort_column} #{sort_direction}"
    end
  end

  def searched_topic_reviews
    topic_reviews = TopicReview

    time_columns = %w[updated_at start_at end_at]
    @time_range_column = time_columns.include?(sort_column) ? sort_column : "created_at"
    topic_reviews.where(@time_range_column => @time_range)
  end

  def searched_topic_review_votes
    topic_review_votes = @topic_review.topic_review_votes.vote_ordered
    if user_subject.present?
      topic_review_votes = topic_review_votes.where(user_id: user_subject.id)
    end
    topic_review_votes
  end

  def permitted_params
    params.require(:topic_review).permit(:topic_name, :timezone, :display_name,
      :start_at_in_zone, :end_at_in_zone)
  end

  def find_topic_review
    @topic_review = TopicReview.find(params[:id])
  end
end

app/views/admin/topic_reviews/_form.html.erb
<% topic_review ||= @topic_review %>
<% editing_topic_review = topic_review.id.present? %>
<% form_url = editing_topic_review ? admin_topic_review_url(topic_review) : admin_topic_reviews_url %>
<%= form_with(model: topic_review, url: form_url, method: (editing_topic_review ? :patch : :post), class: "pb-2") do |f| %>
  <%= render partial: "/shared/errors", locals: {obj: topic_review, name: "Topic Review"} %>
  <%= f.hidden_field :timezone, class: "hiddenFieldTimezone" %>
  <div class="row sm:grid-cols-2">
    <div class="col">
      <div class="form-row">
        <%= f.label :display_name %>
        <%= f.text_field :display_name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col">
      <div class="form-row">
        <%= f.label :topic_name, "Topic" %>
        <%= f.text_field :topic_name, value: (@topic_review.non_topic_name? ? @topic_review.topic_name : ""), class: "form-control", placeholder: "Leave blank unless different from display name" %>
      </div>
    </div>

  </div>
  <div class="row sm:grid-cols-2 mb-8">
    <div class="col">
      <div class="form-row">
        <%= f.label :start_at_in_zone, "Start" %>
        <%= f.datetime_local_field :start_at_in_zone, class: "form-control" %>
      </div>
    </div>
    <div class="col">
      <div class="form-row">
        <%= f.label :end_at_in_zone, "End" %>
        <%= f.datetime_local_field :end_at_in_zone, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-row-btn">
    <%= f.submit "save", class: "btn" %>
  </div>
<% end %>

app/views/admin/topic_reviews/_votes_table.html.erb
<% topic_review_votes ||= @topic_review_votes %>
<% render_sortable ||= false %>
<% skip_article ||= false %>

<div class="">
  <table class="table table-sm break-words max-w-full">
    <thead class="sortable">
      <tr>
        <th>Score</th>
        <th><small>Manual?</small></th>
        <th>
          <%= sortable "created_at", "Rated", skip_sortable: !render_sortable %>
        </th>
        <th>
          <%= sortable "user_id", skip_sortable: !render_sortable %>
        </th>
        <% unless skip_article %>
          <td>Article</td>
        <% end %>
        <th class="break-normal text-center border-r">
          <span title="Agreement">A<span class="hidden md:inline">greement</span></span>
        </th>
        <th class="break-normal text-center border-r">
          <span title="Quality">Q<span class="hidden md:inline">uality</span></span>
        </th>
        <th class="break-normal text-center border-r">
          <span title="Learned something?">L<span class="hidden md:inline">earned <br>
              something?</span></span>
        </th>
        <th class="break-normal text-center border-r">
          <span title="Changed opinion?">C<span class="hidden md:inline">hanged <br>
              opinion?</span></span>
        </th>
        <th class="break-normal text-center border-r">
          <span title="Didn't understand?">D<span class="hidden md:inline">idn't <br>
              understand?</span></span>
        </th>
        <th class="break-normal text-center border-r">
          <span title="Error?">E<span class="hidden md:inline">rror?</span></span>
        </th>
      </tr>
    </thead>
    <tbody>
      <% topic_review_votes.each do |topic_review_vote| %>
        <% rating = topic_review_vote.rating %>
        <tr>
          <td><%= topic_review_vote.vote_score %></td>
          <td><%= check_mark if topic_review_vote.manual_score? %></td>
          <td>
            <span class="convertTime"><%= l(rating.created_at, format: :convert_time) %></span>
          </td>
          <td>
            <%= link_to rating.user&.username, edit_admin_topic_review_path(topic_review_vote.topic_review.to_param, sortable_params.merge(user: rating.user.username)) %>
          </td>
          <% unless skip_article %>
            <td class="max-w-md">
              <%= rating_display(rating) %>
            </td>
          <% end %>
          <td class="text-center border-r">
            <%= agreement_display(rating.agreement) %>
          </td>
          <td class="text-center border-r">
            <%= quality_display(rating.quality) %>
          </td>
          <td class="text-center border-r">
            <%= learned_something_display(rating.learned_something?) %>
          </td>
          <td class="text-center border-r">
            <%= changed_opinion_display(rating.changed_opinion?) %>
          </td>
          <td class="text-center border-r">
            <%= not_understood_display(rating.not_understood?) %>
          </td>
          <td class="text-center border-r">
            <%= significant_factual_error_display(rating.significant_factual_error?) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/topic_reviews/edit.html.erb
<h1 class="standard-top-offset mb-4">
  Edit Topic Review
  <small class="less-strong"><%= link_to "non admin view", review_path(@topic_review.id) %></small>
</h1>
<h3 class="mb-4">Topic: <%= link_to @topic_review.topic.name, edit_admin_topic_path(@topic_review.topic.to_param) %></h3>

<%= render partial: "/admin/topic_reviews/form" %>

<h3 class="standard-top-offset mb-2">Topic Review's Citations</h3>

<div class="row">
  <%= render partial: "tranzito_utils/pagination", locals: {collection: @topic_review_citations, name: "Topic Review Citation"} %>
</div>

<%= render partial: "/admin/topic_review_citations/table", locals: {topic_review_citations: @topic_review_citations, skip_sortable: true} %>

<p class="standard-top-offset mb-2">
  <strong><%= admin_number_display(@topic_review_votes.count) %></strong>
  <%= "Rating".pluralize(@topic_review_votes.count) %>
  <% TopicReviewCitation.ranks.keys.each do |rank| %>
    <small class="inline-block ml-2">
      <strong><%= admin_number_display(@topic_review_votes.where(rank: rank).count) %></strong>
      <%= TopicReviewVote.rank_humanized(rank) %>
    </small>
  <% end %>
</p>
<% if user_subject.present? %>
  <p class="mb-2">
    Showing ratings from <%= user_subject.username %>
    <small class="less-strong">
      show ratings for
      <%= link_to "all users", url_for(sortable_params.merge(user: nil)) %>
    </small>
  </p>
<% end %>

<%= render partial: "/admin/topic_review_votes/table", locals: {topic_review_votes: @topic_review_votes, skip_article: false} %>

<div class="mb-4"></div>

app/views/admin/topic_reviews/index.html.erb
<h1 class="standard-top-offset mb-2">Admin Topic reviews</h1>
<p class="mb-4"><%= link_to "New review", new_admin_topic_review_path, class: "link-primary" %></p>
<%= render partial: "/shared/current_header", locals: {collection: @topic_reviews, render_period: true} %>
<% skip_sortable ||= false %>
<div class="full-screen-table">
  <table class="table table-sm">
    <thead class="sortable">
      <tr>
        <th>
          <%= sortable "created_at", skip_sortable: skip_sortable %>
        </th>
        <th>
          <small><%= sortable "updated_at", skip_sortable: skip_sortable %></small>
        </th>
        <th>
          <%= sortable "display_name", skip_sortable: skip_sortable %>
        </th>
        <th class="small">Topic</th>
        <th>
          Status
        </th>
        <th>
          <%= sortable "start_at", skip_sortable: skip_sortable %>
        </th>
        <th>
          <%= sortable "end_at", skip_sortable: skip_sortable %>
        </th>
        <th>Votes</th>
      </tr>
    </thead>
    <tbody>
      <% @topic_reviews.each do |topic_review| %>
        <tr>
          <td>
            <% if display_dev_info? %><code class="only-dev-visible-small"><%= topic_review.id %></code><% end %>
            <%= link_to l(topic_review.created_at, format: :convert_time), edit_admin_topic_review_path(topic_review), class: "convertTime" %>
          </td>
          <td>
            <small class="convertTime"><%= l(topic_review.updated_at, format: :convert_time) %></small>
          </td>
          <td>
            <%= topic_review.display_name %>
          </td>
          <td>
            <% if topic_review.non_topic_name? %>
              <small><%= topic_review.topic_name %></small>
            <% end %>
          </td>
          <td>
            <%= topic_review.status %>
          </td>
          <td>
            <% if topic_review.start_at.present? %>
              <span class="convertTime"><%= l(topic_review.start_at, format: :convert_time) %></span>
            <% end %>
          </td>
          <td>
            <% if topic_review.end_at.present? %>
              <span class="convertTime"><%= l(topic_review.end_at, format: :convert_time) %></span>
            <% end %>
          </td>
          <td>
            <%= link_to admin_number_display(topic_review.topic_review_votes.count), ratings_path(search_topics: topic_review.topic_name) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/topic_reviews/new.html.erb
<h1 class="standard-top-offset mb-2">New Topic review</h1>
<%= render partial: "/admin/topic_reviews/form" %>