config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  resources :u, only: %i[show edit update] do
    member do
      get :following
      get :followers
    end
  end
  resources :following, only: %i[destroy] do
    member do
      get :add # Use get instead of create so it can store redirect
      post :approve
      post :unapprove
    end
  end

  resources :quizzes, only: %i[index show update]

  root "landing#index"

  get "/about", to: "landing#about"
  get "/privacy", to: "landing#privacy"
  get "/support", to: "landing#support"
  get "/browser_extensions", to: "landing#browser_extensions"
  get "/browser_extension", to: redirect("browser_extensions")
  get "/browser_extension_auth", to: "landing#browser_extension_auth"

  resources :ratings, except: [:show] do
    collection { post :add_topic }
  end

  resources :reviews, only: %i[index show update]

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resource :auth, only: [:create] do
        collection { get :status }
      end
      resources :reviews, only: [:create]
      resources :ratings, only: [:create, :show]
      resources :citations, only: %i[index show] do
        collection { post :filepath }
      end

      match "*a", via: [:get, :post, :put, :patch, :delete], to: "api_v1#not_found"
    end
  end

  namespace :admin do
    root to: "ratings#index"
    resources :users, only: %i[index edit update destroy]
    resources :topics
    resources :topic_reviews, except: [:show]
    resources :topic_review_citations, only: %i[edit update]
    resources :citations, only: %i[index edit update show]
    resources :ratings, only: %i[index show update destroy]
    resources :publishers, only: %i[index edit update show]
    resources :quizzes, except: [:destroy]
    resources :quiz_responses, only: [:index]
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < Admin::BaseController
  include TranzitoUtils::SortableTable

  before_action :set_period, only: %i[index]
  before_action :find_quiz_and_set_page_title, except: %i[index new create]
  before_action :set_form_type, only: %i[new create edit update]

  def index
    page = params[:page] || 1
    @per_page = params[:per_page] || 50
    @quizzes = searched_quizzes.reorder("quizzes.#{sort_column} #{sort_direction}")
      .includes(:citation, :quiz_questions, :quiz_responses).page(page).per(@per_page)
  end

  def show
  end

  def new
    @citation = Citation.friendly_find(params[:citation_id])
    if @citation.present?
      @quiz ||= Quiz.new(citation: @citation)
    else
      flash[:error] = "Unable to find a Citation for the new quiz (citation_id is required)"
      redirect_back(fallback_location: admin_citations_path, status: :see_other)
    end
  end

  def create
    @quiz = Quiz.new(permitted_params)
    if @quiz.save
      flash[:success] = "Quiz created"
      redirect_to admin_quiz_path(@quiz), status: :see_other
    else
      render :new, status: :see_other
    end
  end

  def edit
  end

  def update
    if params[:update_disabledness].present?
      update_status = (params[:update_disabledness] == "disabled") ? "disabled" : "active"
      if @quiz.disableable? || @quiz.disabled?
        if @quiz.update(status: update_status)
          flash[:success] = "Quiz #{params[:update_disabledness]}"
        else
          flash[:error] = @quiz.errors.full_messages.to_sentence
        end
      else
        flash[:error] = "Can't disable quiz, it's currently #{@quiz.status}"
      end
      redirect_to admin_quiz_path(@quiz), status: :see_other
    else
      @new_quiz = Quiz.new(permitted_params)
      if @new_quiz.save
        flash[:success] = "New Quiz version created"
        redirect_to admin_quiz_path(@new_quiz), status: :see_other
      else
        # assign the new attributes to the old quiz
        @quiz.attributes = @new_quiz.slice(permitted_params.keys)
        # And add in the errors
        @new_quiz.errors.each { |e| @quiz.errors.add(e.attribute, e.type) }
        render :edit, status: :see_other
      end
    end
  end

  private

  def permitted_form_types
    %w[admin_entry claude_admin_submission].freeze
  end

  def sortable_columns
    %w[created_at subject citation_id status version source].freeze
  end

  def searchable_statuses
    @searchable_statuses ||= %w[all current not_replaced] + Quiz.statuses.keys.map(&:to_s)
  end

  def selected_form_type(form_type = nil)
    permitted_form_types.include?(form_type) ? form_type : permitted_form_types.first
  end

  def set_form_type
    passed_type = params.dig(:quiz, :source) || params[:form_type]
    @form_type = selected_form_type(passed_type)
  end

  def searched_quizzes
    quizzes = Quiz

    if params[:search_citation_id].present?
      @searched_citation = Citation.friendly_find(params[:search_citation_id])
      quizzes = quizzes.where(citation_id: @searched_citation.id) if @searched_citation.present?
    end

    @search_status = if searchable_statuses.include?(params[:search_status])
      params[:search_status]
    else
      searchable_statuses.first
    end
    quizzes = quizzes.send(@search_status)

    if params[:search_source].present?
      @search_source = params[:search_source]
      quizzes = quizzes.where(source: @search_source)
    end

    quizzes.where(created_at: @time_range)
  end

  def permitted_params
    params.require(:quiz)
      .permit(:citation_id, :input_text, :prompt_params_text, :prompt_text, :subject)
      .merge(source: selected_form_type(params.dig(:quiz, :source)))
  end

  def find_quiz_and_set_page_title
    if params[:citation_id].present?
      @citation = Citation.friendly_find!(params[:citation_id])
      @quiz = @citation.quizzes.current.last
    else
      @quiz = Quiz.find(params[:id])
      @citation = @quiz.citation
    end
    @quiz_questions = @quiz.quiz_questions.includes(:quiz_question_answers)
    @page_title = "Quiz: #{@quiz.title}"
    @page_title += " #{action_name}" unless action_name == "show"
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :redirect_to_signup_unless_user_present!, except: %i[index show]
  before_action :find_quiz_and_response, except: [:index]

  def index
    page = params[:page] || 1
    @per_page = params[:per_page] || 50
    @quizzes = searched_quizzes.page(page).per(@per_page)
      .includes(:quiz_responses)
  end

  def show
    @quiz_questions = @quiz.quiz_questions.includes(:quiz_question_answers)
    @quiz_question_responses = @quiz_response.quiz_question_responses
    @page_title = "Quiz: #{@quiz.title}"
  end

  def update
    @quiz_response.save! unless @quiz_response.id.present?
    if params[:quality].present?
      update_quiz_question_response(@quiz_response, params[:quiz_question_id], params[:quality])
    else
      quiz_question_response = QuizQuestionResponse.new(quiz_response: @quiz_response,
        quiz_question_answer_id: params[:quiz_question_answer_id])
      unless quiz_question_response.save
        flash[:error] = quiz_question_response.errors.full_messages
      end
    end

    # NOTE: redirect with anchor and see_other doesn't work, see https://github.com/hotwired/turbo/issues/211
    # Scrolling to the anchor is handled via JS :/
    redirect_to quiz_path(@quiz.to_param), status: :see_other
  end

  private

  def searched_quizzes
    quizzes = Quiz.active
    if current_user.present?
      # TODO: join stuff
      @quiz_response_finished_ids = current_user.quiz_responses.finished.pluck(:quiz_id)
      @quizzes_completed = TranzitoUtils::Normalize.boolean(params[:search_completed])

      quizzes = if @quizzes_completed
        quizzes.where(id: @quiz_response_finished_ids)
      else
        @quiz_response_in_progress_ids = current_user.quiz_responses.in_progress.pluck(:quiz_id)
        quizzes.where.not(id: @quiz_response_finished_ids)
      end
    end

    @quiz_ordered = TranzitoUtils::Normalize.boolean(params[:search_quiz_ordered])
    if @quiz_ordered
      quizzes.order(id: :desc)
    else
      quizzes.citation_ordered
    end
  end

  def update_quiz_question_response(quiz_response, quiz_question_id, quality)
    quiz_question_response = quiz_response.quiz_question_responses.where(quiz_question_id: quiz_question_id).first
    if quiz_question_response.present?
      if QuizQuestionResponse.qualities.key?(quality)
        quiz_question_response.update!(quality: quality)
      else
        flash[:error] = "Invalid quality: #{quality}"
      end
    else
      flash[:error] = "You must respond to the question before you rate the question"
    end
  end

  def find_quiz_and_response
    # TODO: make friendly find via citation
    @quiz = Quiz.find(params[:id])
    quiz_response = current_user&.quiz_responses&.where(quiz_id: @quiz.id)&.first
    @quiz_response = quiz_response || QuizResponse.new(quiz: @quiz, user: current_user)
  end
end

app/views/admin/quizzes/_form.html.erb
<% quiz ||= @quiz %>
<% citation = quiz.citation %>
<% form_type = @form_type || "admin_entry" %>
<% editing_quiz = quiz.id.present? %>
<% form_url = editing_quiz ? admin_quiz_url(quiz) : admin_quizzes_url %>
<% quiz.input_text&.strip! # Unclear why there is extra space at the start %>

<%= form_with(model: quiz, url: form_url, method: (editing_quiz ? :patch : :post), class: "pb-2") do |f| %>
  <%= render partial: "/shared/errors", locals: {obj: quiz, name: "Quiz"} %>
  <%= f.hidden_field :source, value: form_type %>
  <%= f.hidden_field :citation_id %>

  <% if form_type == "admin_entry" %>
    <div class="form-row mb-4">
      <%= f.label :subject do %>
        Quiz Subject
        <small class="less-strong">
          <% if citation.manually_updated_subject? %>
            The citation's subject was manually updated in admin, which overrides the quiz subject.
          <% else %>
            updating this will also update the citation subject
          <% end %>
        </small>
      <% end %>
      <%= f.text_field :subject, class: "form-control", required: true, disabled: citation.manually_updated_subject? %>
    </div>
    <h2>Manually enter text to generate quiz questions</h2>
    <div class="row sm:grid-cols-3 mt-4 mb-2">
      <div class="col col-span-2">
        <div class="form-row">
          <%# Remove the subject block from the input_text, because there is a subject field %>
          <% quiz.input_text = ClaudeParser::SecondPrompt.quiz_prompt_full_texts(quiz.input_text, citation).first %>
          <%= f.text_area :input_text, class: "form-control", required: true, rows: 15 %>
        </div>
      </div>
      <div class="col pt-1 sm:pt-3">
        <p class="text-sm">Text should have at least one step, and be formatted like this:</p>

        <code class="code-small block mt-2">
          Step 1: {question text}<br />
          <br />
          True option: {true option text}<br />
          <br />
          False option: {false option text}
        </code>
      </div>
    </div>
  <% else %>
    <h2>Input the prompt for Claude to generate the quiz</h2>
    <div class="form-row">
      <%= f.text_area :prompt_text, value: prompt_text_area_text(@quiz.prompt_text), class: "form-control", required: true, rows: 15 %>
      <p class="text-sm -mt-1 mb-3 less-strong">
        <code>[ARTICLE_TEXT]</code> will be replaced with the actual article text. Separating the prompt with <code>---</code> makes a separate request to Claude.
      </p>
    </div>
  <% end %>

  <div class="form-row-btn">
    <%= f.submit "save", class: "btn" %>
  </div>

  <% if form_type != "admin_entry" %>
    <div class="form-row">
      <%= f.label :prompt_params_text do %>
        Additional options for Claude. <strong>Must be valid JSON</strong>
        <small class="less-strong">
          e.g. <code class="text-xs">{"temperature": 0.7}</code>
        </small>
      <% end %>
      <%= f.text_area :prompt_params_text, class: "form-control", rows: 2 %>
    </div>
  <% end %>
<% end %>

<% if form_type != "admin_entry" && editing_quiz %>
  <div class="mt-8 mb-4">
    <span class="less-strong">Previous prompt response:</span>
    <textarea class="form-control text-sm" disabled=true rows="15"><%= @quiz.input_text %></textarea>
  </div>
<% end %>

app/views/admin/quizzes/_quiz_questions_table.html.erb
<% skip_sortable ||= false %>
<% quizzes ||= @quizzes %>
<% skip_citation ||= false %>

<div class="full-screen-table">
  <table class="table table-sm">
    <thead class="sortable">
      <tr>
        <th>
          <%= sortable "created_at", skip_sortable: skip_sortable %>
        </th>
        <th>
          <%= sortable "list_order", skip_sortable: skip_sortable %>
        </th>
        <th>
          <%= sortable "text", skip_sortable: skip_sortable %>
        </th>
        <th>
          <small>Answers</small>
        </th>
      </tr>
    </thead>
    <tbody>
      <% quiz_questions.each do |quiz_question| %>
        <tr>
          <td>
            <% if display_dev_info? %><code class="only-dev-visible-small"><%= quiz_question.id %></code><% end %>
            <span class="convertTime"><%= l(quiz_question.created_at, format: :convert_time) %></span>
          </td>
          <td>
            <code><%= quiz_question.list_order %></code>
          </td>
          <td>
            <%= quiz_question.text.html_safe %>
            <ul>
              <% quiz_question.quiz_question_answers.each do |answer| %>
                <li class="text-sm list-disc pl-5">
                  <strong><%= answer.correct ? "Correct" : "Incorrect" %>:</strong>
                  <%= answer.text %>
                </li>
              <% end %>
            </ul>
          </td>
          <td>
            <%= admin_number_display(quiz_question.quiz_question_answers.count) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/quizzes/_show_header.html.erb
<% reload_if_pending ||= false %>

<div class="large-width-container mt-4">
  <table class="table-list">
    <tbody>
      <tr>
        <td>Citation</td>
        <td><%= admin_citation_cell(@citation, filter_link: admin_citations_path) %></td>
      </tr>
      <tr>
        <td>Subject</td>
        <td>
          <%= @quiz.subject %>
          <% if display_dev_info? %>
            <small class="only-dev-visible ml-1"><%= @quiz.subject_source || 'NO SOURCE!' %></small>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="row sm:grid-cols-2 mt-4">
    <div class="col">
      <table class="table-list">
        <tbody>
          <tr>
            <td>Created</td>
            <td>
              <span class="convertTime"><%= l(@quiz.created_at, format: :convert_time) %></span>
            </td>
          </tr>
          <% if false %>
            <tr class="small">
              <td class="only-dev-visible">Updated</td>
              <td>
                <small class="convertTime"><%= l(@quiz.updated_at, format: :convert_time) %></small>
              </td>
            </tr>
          <% end %>
          <tr>
            <td>Status</td>
            <td>
              <%= admin_status_display(@quiz.status) %>
              <% current_quiz = @quiz.associated_quizzes_current %>
              <% if current_quiz.present? && current_quiz != @quiz %>
                <span class="ml-1">
                  <%= link_to "current quiz is V#{current_quiz.version}", admin_quiz_path(current_quiz.to_param) %>
                </span>
              <% end %>
              <% if @quiz.pending? %>
                <%# Only reload the page automatically if reload_if_pending is passed in, and the quiz is recent %>
                <% if reload_if_pending && @quiz.created_at > Time.current - 5.minutes %>
                  <small data-controller="reload-page-timer">waiting on Claude, reloading in <span id="reloadPageSeconds">10</span> seconds</small>
                <% else %>
                  <% if @quiz.created_at < Time.current - 5.minutes %>
                    <small>prompting failed</small>
                  <% end %>
                  <a href="#" class="text-sm less-strong ml-2" id="reloadLink">reload</a>
                  <script>
                    document.querySelector('#reloadLink').addEventListener('click', (e) => {
                      e.preventDefault()
                      location.reload();
                    })
                  </script>
                <% end %>
              <% elsif @quiz.input_text_parse_error.present? %>
                <span class="block">
                  <strong>Error message:</strong>
                  <%= @quiz.input_text_parse_error %>
                </span>
              <% elsif @quiz.status == "replaced" %>
                <% replaced_by = @quiz.associated_quizzes_following.first %>
                <% if replaced_by.present? && replaced_by != current_quiz %>
                  <em class="ml-2 text-sm less-strong">
                    replaced by
                    <%= link_to "V#{replaced_by.version}", admin_quiz_path(replaced_by) %>&nbsp;
                    <span class="less-strong convertTime withPreposition"><%= l(replaced_by.created_at, format: :convert_time) %></span>
                  </em>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr class="text-sm">
            <td>Version</td>
            <td>
              V<%= @quiz.version %>
              <%= link_to search_emoji, admin_quizzes_path(search_citation_id: @quiz.citation_id), class: "text-sm no-underline mr-2" %>
              <% if @quiz.version > 1 %>
                <em class="text-sm less-strong">earlier versions:</em>
                <%= safe_join(@quiz.associated_quizzes_previous.reorder(id: :desc).map { |pquiz| link_to("V#{pquiz.version}", admin_quiz_path(pquiz.to_param), class: "ml-1 text-sm less-strong italic") }, ", ") %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table-list">
        <tbody>
          <tr>
            <td>Source</td>
            <td>
              <%= @quiz.source_humanized %>
            </td>
          </tr>
          <tr>
            <td>Kind</td>
            <td>
              <%= @quiz.kind_humanized %>
              <% if @quiz.input_text_format.present? %>
                <small class="less-strong ml-2">format: <code><%= @quiz.input_text_format %></code></small>
              <% end %>
            </td>
          </tr>
          <tr class="text-sm">
            <td>Responses</td>
            <td>
              <%= link_to admin_quiz_responses_path(search_quiz_id: @quiz.id) do %>
                <%= admin_number_display(@quiz.quiz_responses.count) %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/quizzes/_table.html.erb
<% skip_sortable ||= false %>
<% quizzes ||= @quizzes %>
<% skip_citation ||= false %>

<div class="full-screen-table">
  <table class="table table-sm">
    <thead class="sortable">
      <tr>
        <th>
          <%= sortable "created_at", skip_sortable: skip_sortable %>
        </th>
        <th>
          <%= sortable "subject", skip_sortable: skip_sortable, class: "sortable-link-narrow italic" %>
          <% unless skip_citation %>
            <%= sortable "citation_id",  skip_sortable: skip_sortable, class: "sortable-link-narrow" %>
          <% end %>
          <th>
            <%= sortable "status", skip_sortable: skip_sortable %>
          </th>
          <th>
            <%= sortable "source", skip_sortable: skip_sortable %>
          </th>
          <th>
            <%= sortable "version", skip_sortable: skip_sortable %>
          </th>
          <th>
            <small>Questions</small>
          </th>
          <th>
            Responses
          </th>
        </tr>
      </thead>
      <tbody>
        <% quizzes.each do |quiz| %>
          <tr>
            <td>
              <% if display_dev_info? %><code class="only-dev-visible-small"><%= quiz.id %></code><% end %>
              <%= link_to l(quiz.created_at, format: :convert_time), admin_quiz_path(quiz), class: "convertTime link" %>
            </td>
            <td class="max-w-md maxWScreen">
              <p class="italic"><%= quiz.subject %></p>
              <% unless skip_citation %>
                <%= admin_citation_cell(quiz.citation) %>
              </td>
            <% end %>
            <td>
              <%= admin_status_display(quiz.status) %><% unless skip_sortable %>&nbsp;<%= link_to search_emoji, url_for(sortable_params.merge(search_status: quiz.status)), class: "text-xs no-underline" %><% end %>
            </td>
            <td>
              <span class="text-sm"><%= quiz.source_humanized %></span><% unless skip_sortable %>&nbsp;<%= link_to search_emoji, url_for(sortable_params.merge(search_source: quiz.source)), class: "text-xs no-underline" %><% end %>
            </td>
            <td>
              V<%= quiz.version %>
              <% unless skip_sortable %> <%= link_to search_emoji, admin_quizzes_path(search_citation_id: quiz.citation_id), class: "text-xs no-underline mr-2" %><% end %>
            </td>
            <td>
              <%= admin_number_display(quiz.quiz_questions.count) %>
            </td>
            <td>
              <%= link_to admin_number_display(quiz.quiz_responses.count), admin_quiz_responses_path(search_quiz_id: quiz.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/admin/quizzes/edit.html.erb
<%= content_for :main_wrapper_class, "container-padded" %>
<div class="large-width-container mb-4">
  <h1 class="standard-top-offset">
    Edit Quiz
    <small class="less-strong">
      <%= quiz_title_display(@quiz) %></small>
  </h1>
</div>

<%= render partial: "show_header" %>

<div class="large-width-container mt-8">
  <div class="mt-4">
    <%= render partial: "form", locals: {quiz: @quiz} %>
  </div>
</div>

app/views/admin/quizzes/index.html.erb
<%= content_for :main_wrapper_class, "container-padded" %>
<div class="large-width-container">
  <h1 class="standard-top-offset mb-6">Admin Quizzes</h1>

  <% if @search_source.present? %>
    <p class="mb-2">
      Quizzes from source:
      <strong><%= Quiz.source_humanized(@search_source) %></strong>
      <em class="less-strong">
        &ndash; view quizzes for
        <%= link_to "all sources", url_for(sortable_params.merge(search_source: nil)) %>
      </em>
    </p>
  <% end %>
  <%= render partial: "/shared/current_header", locals: {collection: @quizzes, render_period: true} %>
</div>

<%= render partial: "table", locals: {quizzes: @quizzes, skip_sortable: false} %>

<%= render partial: "tranzito_utils/pagination", locals: {collection: @quizzes, skip_total: true} %>

app/views/admin/quizzes/new.html.erb
<%= content_for :main_wrapper_class, "container-padded" %>
<div class="large-width-container">
  <h1 class="standard-top-offset">
    New Quiz
  </h1>
</div>

<div class="large-width-container mt-4 mb-8">
  <span class="font-bold block">Citation:</span>
  <%= admin_citation_cell(@citation, filter_link: admin_citations_path) %>
</div>

<div class="large-width-container mt-4">
  <%= render partial: "form", locals: {quiz: @quiz} %>
</div>

app/views/admin/quizzes/show.html.erb
<%= content_for :main_wrapper_class, "container-padded" %>
<div class="large-width-container mb-4">
  <h1 class="standard-top-offset">
    Quiz
    <small class="less-strong"><%= quiz_title_display(@quiz) %></small>
  </h1>

  <p class="text-lg mt-2 mb-4"><%= link_to "Take quiz", quiz_path(@quiz) %></p>

  <%= render partial: "show_header", locals: {reload_if_pending: true} %>
</div>

<div class="large-width-container mt-8">
  <% if !@quiz.prompt_source? %>
    <%# NOTE: input_text duplicated below %>
    <div class="form-row">
      <label><%= quiz_input_text_label_name(@quiz) %></label>
      <textarea class="form-control text-sm" disabled=true rows="15"><%= @quiz.input_text %></textarea>
    </div>
  <% else %>
    <div class="row sm:grid-cols-2">
      <div class="col">
        <div class="form-row">
          <label>Prompt</label>
          <textarea class="form-control text-sm" disabled=true rows="15"><%= prompt_text_area_text(@quiz.prompt_text) %></textarea>
        </div>
      </div>
      <div class="col">
        <%# NOTE: input_text duplicated above %>
        <div class="form-row">
          <label><%= quiz_input_text_label_name(@quiz) %></label>
          <textarea class="form-control text-sm" disabled=true rows="15"><%= @quiz.input_text %></textarea>
        </div>
      </div>
    </div>
    <% if @quiz.prompt_params.present? %>
      <div class="form-row mb-2 text-sm">
        <label>Additional Claude options</label>
        <div class="code-small">
          <%= pretty_print_json(@quiz.prompt_params) %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="mt-6 mb-4">
    <% if @quiz.disabled? %>
      <%= button_to "re-enable quiz", admin_quiz_path(@quiz.to_param, update_disabledness: "re-enabled"), method: :patch, class: "btn mr-2 italic" %>
    <% elsif @quiz.disableable? %>
      <%= button_to "Disable quiz", admin_quiz_path(@quiz.to_param, update_disabledness: "disabled"), method: :patch, class: "btn mr-2 text-yellow-600" %>
    <% else %>
      <span class="less-strong mr-2">Can't disable, not active</span>
    <% end %>
    <%= link_to "Manually update quiz text", edit_admin_quiz_path(@quiz.to_param, form_type: "admin_entry"), class: "btn mr-2" %>
    <%= link_to "Resubmit with a new prompt", edit_admin_quiz_path(@quiz.to_param, form_type: "claude_admin_submission"), class: "btn" %>
  </div>
  <h2 class="standard-top-offset mb-4">
    <%= admin_number_display(@quiz_questions.count) %>
    <%= "Questions".pluralize(@quiz_questions) %>
  </h2>
</div>

<%= render partial: "/admin/quizzes/quiz_questions_table", locals: {quiz_questions: @quiz_questions, skip_sortable: true} %>

<% if display_dev_info? && !@quiz.parse_errored? && @quiz.input_text.present? %>
  <div class="large-width-container my-4">
    <p class="only-dev-visible">Quiz Text Parsed</p>
    <div class="code-small">
      <%= pretty_print_json(QuizParseAndCreateQuestionsJob.parsed_quiz_text(@quiz)) %>
    </div>

    <p class="only-dev-visible mt-5">Subject Text Parsed</p>
    <div class="code-small">
      <%= pretty_print_json(QuizParseAndCreateQuestionsJob.parsed_subject_text(@quiz)) %>
    </div>
  </div>
<% end %>