config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  resources :u, only: %i[show edit update] do
    member do
      get :following
      get :followers
    end
  end
  resources :following, only: %i[destroy] do
    member do
      get :add # Use get instead of create so it can store redirect
      post :approve
      post :unapprove
    end
  end

  resources :quizzes, only: %i[index show update]

  root "landing#index"

  get "/about", to: "landing#about"
  get "/privacy", to: "landing#privacy"
  get "/support", to: "landing#support"
  get "/browser_extensions", to: "landing#browser_extensions"
  get "/browser_extension", to: redirect("browser_extensions")
  get "/browser_extension_auth", to: "landing#browser_extension_auth"

  resources :ratings, except: [:show] do
    collection { post :add_topic }
  end

  resources :reviews, only: %i[index show update]

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resource :auth, only: [:create] do
        collection { get :status }
      end
      resources :reviews, only: [:create]
      resources :ratings, only: [:create, :show]
      resources :citations, only: %i[index show] do
        collection { post :filepath }
      end

      match "*a", via: [:get, :post, :put, :patch, :delete], to: "api_v1#not_found"
    end
  end

  namespace :admin do
    root to: "ratings#index"
    resources :users, only: %i[index edit update destroy]
    resources :topics
    resources :topic_reviews, except: [:show]
    resources :topic_review_citations, only: %i[edit update]
    resources :citations, only: %i[index edit update show]
    resources :ratings, only: %i[index show update destroy]
    resources :publishers, only: %i[index edit update show]
    resources :quizzes, except: [:destroy]
    resources :quiz_responses, only: [:index]
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  include FriendlyFindable

  has_many :rating_topics
  has_many :ratings, through: :rating_topics
  has_many :citation_topics
  has_many :citations, through: :citation_topics
  has_many :topic_reviews
  has_many :topic_review_votes, through: :topic_reviews

  has_many :parent_relations, class_name: "TopicRelation", foreign_key: :child_id, dependent: :destroy
  has_many :parents, through: :parent_relations, source: :parent
  has_many :child_relations, class_name: "TopicRelation", foreign_key: :parent_id, dependent: :destroy
  has_many :children, through: :child_relations, source: :child

  has_many :direct_parent_relations, -> { direct }, class_name: "TopicRelation", foreign_key: :child_id, dependent: :destroy
  has_many :direct_parents, through: :direct_parent_relations, source: :parent
  has_many :direct_child_relations, -> { direct }, class_name: "TopicRelation", foreign_key: :parent_id, dependent: :destroy
  has_many :direct_children, through: :direct_child_relations, source: :child

  validates_uniqueness_of :name, case_sensitive: false
  validates :name, format: {without: /,/, message: "can't contain commas"}
  validate :slug_uniq_if_name_uniq

  before_validation :set_calculated_attributes
  after_commit :update_associations

  scope :name_ordered, -> { order(arel_table["name"].lower) }
  scope :active, -> { where(orphaned: false) }
  scope :orphaned, -> { where(orphaned: true) }

  attr_accessor :skip_update_associations, :skip_distant_children

  class << self
    def without_parent
      select { |t| t.parents.limit(1).none? }
    end

    def slugify(str = nil)
      Slugifyer.slugify_and(str)
    end

    # Overrides FriendlyFindable
    def friendly_find_slug(str = nil)
      return nil if str.blank?
      slug = slugify(str)
      # Find by singular before find_by_previous, so it doesn't revert update
      find_by_slug(slug) || find_by_singular(slug) || find_by_previous_slug(slug)
    end

    def find_or_create_for_name(name, attrs = {update_attrs: false})
      @found_plural, @found_singular = false, false
      existing = friendly_find(name) || friendly_find_plural(name)
      if existing.present?
        if attrs[:update_attrs]
          # Don't update if the new name is a plural (or unchanged)
          if !@found_singular && existing.name != name.strip
            if @found_plural
              existing.name = name
            elsif name.match("&") && existing.name.match?(/\band\b/i) && !existing.name.match("&")
              # Don't switch to "&" if existing uses "and"
            else
              existing.name = name
            end
          end
          existing.update(attrs.except(:update_attrs))
        end
        existing
      else
        create(attrs.except(:update_attrs).merge(name: name))
      end
    end

    def friendly_find_all(arr = nil)
      return [] if arr.blank?
      arr.flatten.map { |s| friendly_find(s) }.compact
    end

    def friendly_find_all_parentless(arr = nil)
      topics = friendly_find_all(arr)
      topic_ids = topics.pluck(:id)
      topics.reject do |topic|
        topic.child_relations.where(child_id: topic_ids).limit(1).any?
      end
    end

    def child_ids_for_ids(ids)
      TopicRelation.where(parent_id: ids).pluck(:child_id)
    end

    def admin_search(str)
      where("name ILIKE ?", "%#{str.strip}%")
    end

    private

    def find_by_singular(str)
      singular = str.singularize
      return nil if singular == str
      result = find_by_slug(singular)
      @found_singular = result.present?
      result
    end

    # This is only used for create, not in normal friendly_find
    def friendly_find_plural(str)
      result = find_by_slug(slugify(str&.pluralize))
      @found_plural = result.present?
      result
    end
  end

  def to_param
    slug
  end

  def parents_string=(val)
    parent_ids = self.class.friendly_find_all(val&.split(",")).map(&:id)
    parent_relations.where.not(parent_id: parent_ids).destroy_all
    new_ids = parent_ids - parent_relations.pluck(:parent_id)
    parent_relations.distant.update_all(direct: true)
    new_ids.each { |i| parent_relations.build(parent_id: i, direct: true) }
  end

  def parents_string
    direct_parent_names.join(", ")
  end

  # May get more complicated someday...
  def direct_parent_names
    direct_parents.name_ordered.pluck(:name)
  end

  def active?
    !orphaned
  end

  def set_calculated_attributes
    self.orphaned = calculated_orphaned?
    self.name = name&.strip
    old_slug = slug
    self.slug = self.class.slugify(name)
    self.previous_slug = self.class.slugify(previous_slug)
    if old_slug.present? && old_slug != slug
      self.previous_slug = old_slug
    end
  end

  def slug_uniq_if_name_uniq
    if slug.blank?
      errors.add(:name, "can't be blank")
    elsif slug.match?(/\A\d+\z/)
      errors.add(:name, "can't be only numbers")
    end
    name_errors = errors.messages[:name]
    # Validating uniqueness of name_slug here because:
    # - we don't want to say "name_slug"
    # - don't duplicate the error if the name is already non-unique
    return true if name_errors.include?("has already been taken")
    topics = id.present? ? Topic.where.not(id: id) : Topic
    return true if topics.where(slug: slug).none?
    errors.add(:name, "has already been taken")
  end

  def update_associations
    return true if skip_update_associations
    topic_reviews.each { |ti| ti.update(updated_at: Time.current) }
    enqueue_rating_reconcilliation
    return true if skip_distant_children
    DistantChildCreatorJob.perform_async(id)
  end

  def enqueue_rating_reconcilliation
    ratings.pluck(:id).each { |i| ReconcileRatingTopicsJob.perform_async(i) }
  end

  private

  def calculated_orphaned?
    rating_topics.none?
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController
  include TranzitoUtils::SortableTable

  before_action :set_period, only: [:index]
  before_action :find_topic, except: [:index, :new, :create]

  def index
    page = params[:page] || 1
    @per_page = params[:per_page] || 200
    @topics = searched_topics.reorder("topics.#{sort_column} #{sort_direction}")
      .includes(:rating_topics).page(page).per(@per_page)
  end

  def show
    redirect_to edit_admin_topic_path(params[:id])
    nil
  end

  def new
    @topic ||= Topic.new
  end

  def create
    @topic = Topic.new(permitted_params)
    if @topic.save
      flash[:success] = "Topic created"
      redirect_to admin_topics_path, status: :see_other
    else
      render :new, status: :see_other
    end
  end

  def edit
  end

  def update
    if @topic.update(permitted_params)
      flash[:success] = "Topic updated"
      redirect_to edit_admin_topic_path(@topic), status: :see_other
    else
      render :edit, status: :see_other
    end
  end

  def destroy
    @topic.destroy
    flash[:success] = "Topic removed"
    redirect_to admin_topics_path, status: :see_other
  end

  private

  def sortable_columns
    %w[created_at slug updated_at previous_slug]
  end

  def searched_topics
    topics = Topic

    topics = topics.admin_search(params[:query]) if params[:query].present?

    @time_range_column = (sort_column == "updated_at") ? "updated_at" : "created_at"
    topics.where(@time_range_column => @time_range)
  end

  def permitted_params
    params.require(:topic).permit(:name, :parents_string, :previous_slug)
  end

  def find_topic
    @topic = Topic.friendly_find!(params[:id])
  end
end

app/views/admin/topics/_form.html.erb
<% topic ||= @topic %>
<% editing_topic = topic.id.present? %>
<% form_url = editing_topic ? admin_topic_url(topic) : admin_topics_url %>
<%= form_with(model: topic, url: form_url, method: (editing_topic ? :patch : :post), class: "pb-2") do |f| %>
  <%= render partial: "/shared/errors", locals: {obj: topic, name: "Topic"} %>
  <%= f.hidden_field :timezone, class: "hiddenFieldTimezone" %>
  <div class="row sm:grid-cols-2">
    <div class="col">
      <div class="form-row">
        <%= f.label :name, "Topic" %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col">
      <div class="form-row">
        <%= f.label :previous_slug do %>
          Previous name
          <small class="less-strong">Overridden/updated when name changes</small>
        <% end %>
        <%= f.text_field :previous_slug, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <%= f.label :parents_string do %>
      Parent topics
      <small class="less-strong">
        Only include <em>direct</em> parents. Does <strong>not</strong> create new topics. Comma delineated
      </small>
    <% end %>
    <%= f.text_field :parents_string, class: "form-control" %>
  </div>
  <div class="form-row-btn">
    <%= f.submit "save", class: "btn" %>
  </div>
<% end %>

app/views/admin/topics/_table.html.erb
<% skip_sortable ||= false %>
<% topics ||= @topics %>
<% skip_ratings_count ||= false %>
<div class="full-screen-table">
  <table class="table table-sm">
    <thead class="sortable">
      <tr>
        <th>
          <%= sortable "created_at", skip_sortable: skip_sortable %>
        </th>
        <% if render_updated_at? %>
          <th>
            <small><%= sortable "updated_at", skip_sortable: skip_sortable %></small>
          </th>
        <% end %>
        <th>
          <%= sortable "slug", "Name", skip_sortable: skip_sortable %>
        </th>
        <th>
          <small><%= sortable "previous_slug", "Previously", skip_sortable: skip_sortable %></small>
        </th>
        <th>Parents</th>
        <% unless skip_ratings_count %>
          <th>Ratings</th>
        <% end %>
        <th>
          <small>Active</small>
        </th>
      </tr>
    </thead>
    <tbody>
      <% topics.each do |topic| %>
        <tr>
          <td>
            <% if display_dev_info? %><code class="only-dev-visible-small"><%= topic.id %></code><% end %>
            <span class="convertTime"><%= l(topic.created_at, format: :convert_time) %></span>
          </td>
          <% if render_updated_at? %>
            <td>
              <small class="convertTime"><%= l(topic.updated_at, format: :convert_time) %></small>
            </td>
          <% end %>
          <td>
            <%= link_to topic&.name, edit_admin_topic_path(topic.to_param) %>
            <!-- <% if display_dev_info? %><small class="only-dev-visible-small"><%= topic.slug %></small><% end %> -->
          </td>
          <td>
            <small class="less-strong"><%= topic.previous_slug %></small>
          </td>
          <td>
            <small><%= topic.parents_string %></small>
          </td>
          <td>
            <% unless skip_ratings_count %>
              <%= link_to admin_number_display(topic.rating_topics.count), ratings_path(search_topics: [topic.slug]) %>
            <% end %>
          </td>
          <td class="table-cell-check">
            <%= check_mark if topic.active? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/topics/edit.html.erb
<h1 class="standard-top-offset mb-4">Edit Topic</h1>
<div class="mb-4"><%# must be div, escapes p tag %>
  <%= button_to "Delete topic", {controller: "topics", action: "destroy", id: @topic.id}, method: :delete, class: "gray-link" %>
</div>

<% rating_count = @topic.rating_topics.count %>
<p class="mb-4">
  <%= link_to ratings_path(search_topics: @topic.slug) do %>
    <%= number_with_delimiter(rating_count) %>
    <%= "rating".pluralize(rating_count) %>
  <% end %>
</p>

<%= render partial: "form", locals: {topic: @topic} %>

<h4 class="standard-top-offset">Direct Children</h4>
<%= render partial: "table", locals: {topics: @topic.direct_children, skip_sortable: false} %>

app/views/admin/topics/index.html.erb
<h1 class="standard-top-offset mb-4">Admin topics</h1>
<p class="mb-4"><%= link_to "New topic", new_admin_topic_path, class: "link-primary" %></p>

<%= form_tag admin_topics_path, method: :get do %>
  <%= render partial: "/shared/hidden_search_fields" %>
  <div class="row sm:grid-cols-2 mb-4">
    <div class="col">
      <div class="form-row">
        <%= label_tag :query %>
        <%= text_field_tag :query, params[:query], class: "form-control" %>
      </div>
    </div>
    <div class="col">
      <div class="form-row-btn sm:mt-8">
        <%= submit_tag "search", class: "btn" %>
      </div>
    </div>
  </div>
<% end %>

<%= render partial: "/shared/current_header", locals: {collection: @topics, render_period: true} %>

<%= render partial: "table", locals: {topics: @topics, skip_sortable: false, skip_ratings_count: false} %>

app/views/admin/topics/new.html.erb
<h1 class="standard-top-offset mb-4">New Topic</h1>

<%= render partial: "form", locals: {topic: @topic} %>