config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  resources :u, only: %i[show edit update] do
    member do
      get :following
      get :followers
    end
  end
  resources :following, only: %i[destroy] do
    member do
      get :add # Use get instead of create so it can store redirect
      post :approve
      post :unapprove
    end
  end

  resources :quizzes, only: %i[index show update]

  root "landing#index"

  get "/about", to: "landing#about"
  get "/privacy", to: "landing#privacy"
  get "/support", to: "landing#support"
  get "/browser_extensions", to: "landing#browser_extensions"
  get "/browser_extension", to: redirect("browser_extensions")
  get "/browser_extension_auth", to: "landing#browser_extension_auth"

  resources :ratings, except: [:show] do
    collection { post :add_topic }
  end

  resources :reviews, only: %i[index show update]

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resource :auth, only: [:create] do
        collection { get :status }
      end
      resources :reviews, only: [:create]
      resources :ratings, only: [:create, :show]
      resources :citations, only: %i[index show] do
        collection { post :filepath }
      end

      match "*a", via: [:get, :post, :put, :patch, :delete], to: "api_v1#not_found"
    end
  end

  namespace :admin do
    root to: "ratings#index"
    resources :users, only: %i[index edit update destroy]
    resources :topics
    resources :topic_reviews, except: [:show]
    resources :topic_review_citations, only: %i[edit update]
    resources :citations, only: %i[index edit update show]
    resources :ratings, only: %i[index show update destroy]
    resources :publishers, only: %i[index edit update show]
    resources :quizzes, except: [:destroy]
    resources :quiz_responses, only: [:index]
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include FriendlyFindable

  ROLE_ENUM = {basic_user: 0, admin: 2, developer: 1}.freeze

  devise :database_authenticatable, :registerable, :trackable,
    :recoverable, :rememberable, :validatable

  has_many :ratings
  has_many :citations, through: :ratings
  has_many :events
  has_many :kudos_events
  has_many :user_followings, dependent: :destroy
  has_many :followings, through: :user_followings, source: :following
  has_many :user_followings_approved, -> { approved }, class_name: "UserFollowing"
  has_many :followings_approved, through: :user_followings_approved, source: :following
  has_many :followings_approved_private, -> { account_private }, through: :user_followings_approved, source: :following
  has_many :user_followers, class_name: "UserFollowing", foreign_key: :following_id, dependent: :destroy
  has_many :followers, through: :user_followers, source: :user
  has_many :user_followers_approved, -> { approved }, class_name: "UserFollowing", foreign_key: :following_id, dependent: :destroy
  has_many :followers_approved, through: :user_followers_approved, source: :user
  has_many :topic_review_votes
  has_many :quiz_responses

  enum :role, ROLE_ENUM

  validates_uniqueness_of :username, case_sensitive: false
  validates_with UsernameValidator

  before_validation :set_calculated_attributes
  after_commit :update_followers

  scope :account_private, -> { where(account_private: true) }
  scope :account_public, -> { where(account_private: false) }

  def self.friendly_find_slug(str = nil)
    return nil if str.blank?
    find_by_username_slug(slugify(str))
  end

  def self.admin_search(str)
    val = "%#{str.strip}%"
    where("username ILIKE ?", val)
      .or(where("email ILIKE ?", val))
  end

  # TODO: make this whole thing less terrible and more secure
  def self.generate_api_token
    SecureRandom.urlsafe_base64 + SecureRandom.urlsafe_base64 + SecureRandom.urlsafe_base64
  end

  def rated?(citation_or_id)
    citation_id = citation_or_id.id if citation_or_id.is_a?(Citation)
    citation_id ||= citation_or_id # May accept other models later
    ratings.where(citation_id: citation_id).limit(1).any?
  end

  def admin_access?
    admin? || developer?
  end

  def following_ratings_visible
    Rating.where(user_id: user_followings.ratings_visible.pluck(:following_id))
  end

  def to_param
    username_slug
  end

  def account_public?
    !account_private
  end

  def ratings_public?
    account_public?
  end

  def ratings_private?
    !ratings_public?
  end

  # Need to pass in the timezone here ;)
  def total_kudos_today(timezone = nil)
    kudos_events.created_today(timezone).sum(:total_kudos)
  end

  # Need to pass in the timezone here too
  def total_kudos_yesterday(timezone = nil)
    kudos_events.created_yesterday(timezone).sum(:total_kudos)
  end

  def following?(user_or_id = nil)
    following(user_or_id).limit(1).present?
  end

  def following_approved?(user_or_id = nil)
    following(user_or_id).approved.limit(1).present?
  end

  def follower_approved?(user_or_id = nil)
    follower(user_or_id).approved.limit(1).present?
  end

  def set_calculated_attributes
    self.role ||= "basic_user"
    self.about = nil if about.blank?
    self.api_token = self.class.generate_api_token if new_api_token?
    self.username = username&.strip
    self.username_slug = self.class.slugify(username)
    self.total_kudos ||= 0
    @should_update_followers = account_private_changed?
  end

  def update_followers
    return true unless @should_update_followers
    # Inefficient, but solves the problem
    user_followers.unapproved.each { |f| f.update(updated_at: Time.current) }
    ratings.update_all(account_public: account_public?)
  end

  private

  def following(user_or_id = nil)
    return UserFollowing.none if user_or_id.blank?
    f_id = user_or_id.is_a?(User) ? user_or_id.id : user_or_id
    user_followings.where(following_id: f_id)
  end

  def follower(user_or_id = nil)
    return UserFollowing.none if user_or_id.blank?
    f_id = user_or_id.is_a?(User) ? user_or_id.id : user_or_id
    user_followers.where(user_id: f_id)
  end

  def new_api_token?
    api_token.blank? || encrypted_password_changed?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  include TranzitoUtils::SortableTable

  before_action :set_period, only: [:index]
  before_action :find_user, except: [:index]

  def index
    page = params[:page] || 1
    @per_page = params[:per_page] || 25
    @users = searched_users.reorder("users.#{sort_column} #{sort_direction}")
      .includes(:ratings).page(page).per(@per_page)
  end

  def edit
  end

  def update
    if @user.update(permitted_params)
      flash[:success] = "User updated"
      redirect_to edit_admin_user_path(@user), status: :see_other
    else
      render :edit, status: :see_other
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "Topic removed"
    redirect_to admin_topics_path, status: :see_other
  end

  private

  def sortable_columns
    %w[created_at updated_at email username]
  end

  def searched_users
    users = User

    users = users.admin_search(params[:query]) if params[:query].present?

    @time_range_column = (sort_column == "updated_at") ? "updated_at" : "created_at"
    users.where(@time_range_column => @time_range)
  end

  def permitted_params
    params.require(:user).permit(:username, :role)
  end

  def find_user
    @user = User.friendly_find!(params[:id])
  end
end

app/views/admin/users/edit.html.erb
<h1 class="standard-top-offset mb-4">Edit User</h1>
<div class="mb-4"><%# must be div, escapes p tag %>
  <%= button_to "Delete user", {controller: "users", action: "destroy", id: @user.id}, method: :delete, class: "gray-link" %>
</div>

<div class="row sm:grid-cols-2">
  <div class="col">
    <table class="table-list">
      <tbody>
        <tr>
          <td>Created</td>
          <td>
            <span class="convertTime"><%= l(@user.created_at, format: :convert_time) %></span>
          </td>
        </tr>
        <tr>
          <td>Updated</td>
          <td>
            <small class="convertTime"><%= l(@user.updated_at, format: :convert_time) %></small>
          </td>
        </tr>
        <tr>
          <td>Ratings</td>
          <td>
            <%= link_to admin_number_display(@user.ratings.count), ratings_path(user: @user.username) %>
          </td>
        </tr>
        <tr>
          <td>Followers</td>
          <td>
            <%= link_to admin_number_display(@user.followers_approved.count), followers_u_path(id: @user.to_param) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col">
    <table class="table-list">
      <tbody>
        <tr>
          <td>Private</td>
          <td>
            <%= check_mark if @user.account_private %>
          </td>
        </tr>
        <tr>
          <td>Total Kudos</td>
          <td>
            <%= admin_number_display(@user.total_kudos) %>
          </td>
        </tr>
        <tr>
          <td>Quizzed</td>
          <td>
            <%= link_to admin_number_display(@user.quiz_responses.count), admin_quiz_responses_path(user: @user.username) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<%= form_with(model: @user, url: admin_user_path(@user), method: :patch, class: "mt-8 pb-2") do |f| %>
  <%= render partial: "/shared/errors", locals: {obj: @user, name: "User"} %>

  <div class="row sm:grid-cols-2">
    <div class="col">
      <div class="form-row">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col">
      <div class="form-row">
        <%= f.label :role %>
        <%= f.select :role, User.roles.keys, {required: true}, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-row-btn">
    <%= f.submit "save", class: "btn" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1 class="standard-top-offset mb-4">
  Admin users
  <% if display_dev_info? %>
    <small class="less-strong only-dev-visible text-sm px-1">
      current_user id:
      <%= link_to current_user.id, edit_admin_user_path(current_user) %>
    </small>
  <% end %>
</h1>
<%= render partial: "/shared/current_header", locals: {collection: @users, render_period: true} %>

<% skip_sortable ||= false %>

<div class="full-screen-table mb-4">
  <table class="table table-sm table-striped thead-light">
    <thead class="sortable">
      <tr>
        <th>
          <%= sortable "created_at", skip_sortable: skip_sortable %>
        </th>
        <th>
          <small><%= sortable "updated_at", skip_sortable: skip_sortable %></small>
        </th>
        <th>
          <%= sortable "username", skip_sortable: skip_sortable %>
        </th>
        <th>
          <small><%= sortable "email", skip_sortable: skip_sortable %></small>
        </th>
        <th>Ratings</th>
        <th>
          <small title="Account Private?">P<span class="hidden md:inline">rivate</span></small>
        </th>
        <th><small>Followers</small></th>
        <th>Roles</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <% if display_dev_info? %><code class="only-dev-visible-small"><%= user.id %></code><% end %>
            <span class="convertTime"><%= l(user.created_at, format: :convert_time) %></span>
          </td>
          <td>
            <small class="convertTime"><%= l(user.updated_at, format: :convert_time) %></small>
          </td>
          <td>
            <%= link_to user&.username, edit_admin_user_path(user.id) %>
          </td>
          <td>
            <small><%= user.email %></small>
          </td>
          <td><%= admin_number_display(user.ratings.count) %></td>
          <td class="table-cell-check">
            <%= check_mark if user.account_private %>
          </td>
          <td>
            <%= link_to admin_number_display(user.followers_approved.count), followers_u_path(id: user.to_param) %>
          </td>
          <td>
            <% unless user.basic_user? %>
              <small><%= user.role %></small>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%# add spinner to force including in css %>
<div class="hidden">
  <svg aria-hidden="true" class="w-8 h-8 mr-2 text-gray-200 animate-spin fill-gray-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
    <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
  </svg>

  <%# some more forced classes, for the extension, probably need to have a better place for these %>
  <p class="opacity-50 -mt-1">Stuff</p>
</div>